/* Generated by Yosys 0.66 (git sha1 86f2ddebc-dirty, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "../../rtl/uart_simple.sv:5.1-197.10" *)
module uart_simple(clk_i, rst_ni, tx_start_i, tx_done_o, rx_valid_o, rx_error_o, uart_busy_o, tx_data_i, rx_data_o, uart_rx_i, uart_tx_o);
  (* src = "../../rtl/uart_simple.sv:10.17-10.22" *)
  input clk_i;
  wire clk_i;
  (* src = "../../rtl/uart_simple.sv:11.17-11.23" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../../rtl/uart_simple.sv:14.18-14.28" *)
  input tx_start_i;
  wire tx_start_i;
  (* src = "../../rtl/uart_simple.sv:15.18-15.27" *)
  output tx_done_o;
  wire tx_done_o;
  (* src = "../../rtl/uart_simple.sv:16.18-16.28" *)
  output rx_valid_o;
  wire rx_valid_o;
  (* src = "../../rtl/uart_simple.sv:17.18-17.28" *)
  output rx_error_o;
  wire rx_error_o;
  (* src = "../../rtl/uart_simple.sv:18.18-18.29" *)
  output uart_busy_o;
  wire uart_busy_o;
  (* src = "../../rtl/uart_simple.sv:20.24-20.33" *)
  input [7:0] tx_data_i;
  wire [7:0] tx_data_i;
  (* src = "../../rtl/uart_simple.sv:21.24-21.33" *)
  output [7:0] rx_data_o;
  wire [7:0] rx_data_o;
  (* src = "../../rtl/uart_simple.sv:24.18-24.27" *)
  input uart_rx_i;
  wire uart_rx_i;
  (* src = "../../rtl/uart_simple.sv:25.18-25.27" *)
  output uart_tx_o;
  wire uart_tx_o;
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  wire [5:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  (* src = "../../rtl/uart_simple.sv:61.15-61.22" *)
  wire [2:0] bit_cnt;
  (* src = "../../rtl/uart_simple.sv:44.31-44.38" *)
  wire [5:0] clk_cnt;
  (* src = "../../rtl/uart_simple.sv:74.15-74.27" *)
  wire [7:0] rx_shift_reg;
  (* src = "../../rtl/uart_simple.sv:86.15-86.27" *)
  wire [8:0] tx_shift_reg;
  (* onehot = 32'd1 *)
  wire [3:0] uart_cstate;
  (* src = "../../rtl/uart_simple.sv:100.9-100.18" *)
  wire uart_mode;
  (* src = "../../rtl/uart_simple.sv:40.8-40.24" *)
  wire uart_rx_filtered;
  (* src = "../../rtl/uart_simple.sv:32.15-32.27" *)
  wire [1:0] uart_rx_sync;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _082_ (
    .I(uart_cstate[0]),
    .ZN(uart_busy_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _083_ (
    .I(uart_mode),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _084_ (
    .I(clk_cnt[3]),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _085_ (
    .I(clk_cnt[0]),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _086_ (
    .I(uart_rx_sync[1]),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _087_ (
    .I(tx_shift_reg[8]),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _088_ (
    .I(uart_rx_sync[0]),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _089_ (
    .I(uart_cstate[1]),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _090_ (
    .I(tx_shift_reg[0]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _091_ (
    .A1(clk_cnt[1]),
    .A2(_064_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _092_ (
    .A1(clk_cnt[2]),
    .A2(clk_cnt[5]),
    .A3(uart_mode),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _093_ (
    .A1(clk_cnt[3]),
    .A2(clk_cnt[4]),
    .A3(clk_cnt[1]),
    .A4(_064_),
    .Z(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _094_ (
    .A1(_071_),
    .A2(_072_),
    .Z(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _095_ (
    .A1(_071_),
    .A2(_072_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _096_ (
    .A1(uart_cstate[2]),
    .A2(uart_rx_sync[1]),
    .A3(_073_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _097_ (
    .I(_075_),
    .ZN(rx_error_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _098_ (
    .A1(clk_cnt[1]),
    .A2(_064_),
    .Z(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _099_ (
    .A1(clk_cnt[2]),
    .A2(clk_cnt[5]),
    .A3(_063_),
    .A4(clk_cnt[4]),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _100_ (
    .A1(_076_),
    .A2(_077_),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _101_ (
    .A1(_076_),
    .A2(_077_),
    .Z(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _102_ (
    .A1(uart_rx_sync[1]),
    .A2(_067_),
    .B(tx_start_i),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _103_ (
    .A1(uart_cstate[3]),
    .A2(_078_),
    .B1(_080_),
    .B2(uart_cstate[0]),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _104_ (
    .A1(_075_),
    .A2(_081_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _105_ (
    .A1(uart_cstate[2]),
    .A2(_065_),
    .A3(_071_),
    .A4(_072_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _106_ (
    .A1(uart_busy_o),
    .A2(_026_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _107_ (
    .A1(uart_busy_o),
    .A2(_079_),
    .A3(_026_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _108_ (
    .A1(clk_cnt[2]),
    .A2(clk_cnt[1]),
    .A3(clk_cnt[0]),
    .Z(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _109_ (
    .A1(clk_cnt[3]),
    .A2(_029_),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _110_ (
    .A1(clk_cnt[4]),
    .A2(_030_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _111_ (
    .A1(clk_cnt[4]),
    .A2(_030_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _112_ (
    .A1(_028_),
    .A2(_032_),
    .ZN(_000_[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _113_ (
    .A1(uart_cstate[0]),
    .A2(uart_cstate[2]),
    .A3(uart_cstate[1]),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _114_ (
    .A1(_078_),
    .A2(_033_),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _115_ (
    .A1(_078_),
    .A2(_033_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _116_ (
    .A1(uart_mode),
    .A2(_035_),
    .ZN(rx_valid_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _117_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[0]),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _118_ (
    .A1(bit_cnt[2]),
    .A2(_078_),
    .A3(_036_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _119_ (
    .A1(uart_cstate[1]),
    .A2(bit_cnt[2]),
    .A3(_078_),
    .A4(_036_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _120_ (
    .A1(uart_cstate[3]),
    .A2(_079_),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _121_ (
    .A1(_038_),
    .A2(_039_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _122_ (
    .A1(_062_),
    .A2(_035_),
    .ZN(tx_done_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _123_ (
    .A1(_062_),
    .A2(_079_),
    .B(_074_),
    .C(uart_cstate[2]),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _124_ (
    .A1(uart_busy_o),
    .A2(_080_),
    .B(_040_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _125_ (
    .A1(uart_mode),
    .A2(uart_cstate[2]),
    .A3(_078_),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _126_ (
    .A1(_068_),
    .A2(_037_),
    .B(_041_),
    .C(_026_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _127_ (
    .A1(clk_cnt[3]),
    .A2(_029_),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _128_ (
    .A1(_027_),
    .A2(_030_),
    .A3(_042_),
    .ZN(_000_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _129_ (
    .A1(clk_cnt[1]),
    .A2(clk_cnt[0]),
    .B(clk_cnt[2]),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _130_ (
    .A1(_028_),
    .A2(_029_),
    .A3(_043_),
    .ZN(_000_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _131_ (
    .A1(clk_cnt[5]),
    .A2(_031_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _132_ (
    .A1(_028_),
    .A2(_044_),
    .ZN(_000_[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _133_ (
    .A1(_070_),
    .A2(_076_),
    .B(_028_),
    .ZN(_000_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _134_ (
    .A1(clk_cnt[0]),
    .A2(_027_),
    .ZN(_000_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _135_ (
    .A1(uart_cstate[0]),
    .A2(tx_start_i),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _136_ (
    .A1(uart_cstate[0]),
    .A2(_062_),
    .A3(_076_),
    .A4(_077_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _137_ (
    .A1(uart_cstate[0]),
    .A2(tx_start_i),
    .B(_046_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _138_ (
    .A1(uart_cstate[0]),
    .A2(_062_),
    .A3(_079_),
    .B(_045_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _139_ (
    .I0(tx_data_i[3]),
    .I1(tx_shift_reg[5]),
    .S(_045_),
    .Z(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _140_ (
    .I0(tx_shift_reg[4]),
    .I1(_049_),
    .S(_048_),
    .Z(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _141_ (
    .I0(tx_data_i[2]),
    .I1(tx_shift_reg[4]),
    .S(_045_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _142_ (
    .I0(tx_shift_reg[3]),
    .I1(_050_),
    .S(_048_),
    .Z(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _143_ (
    .I0(tx_data_i[1]),
    .I1(tx_shift_reg[3]),
    .S(_045_),
    .Z(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _144_ (
    .I0(tx_shift_reg[2]),
    .I1(_051_),
    .S(_048_),
    .Z(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _145_ (
    .I0(tx_data_i[0]),
    .I1(tx_shift_reg[2]),
    .S(_045_),
    .Z(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _146_ (
    .I0(tx_shift_reg[1]),
    .I1(_052_),
    .S(_048_),
    .Z(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _147_ (
    .A1(tx_shift_reg[1]),
    .A2(_046_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _148_ (
    .A1(_069_),
    .A2(_048_),
    .B(_053_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _149_ (
    .A1(bit_cnt[0]),
    .A2(_078_),
    .B(bit_cnt[1]),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _150_ (
    .A1(_078_),
    .A2(_036_),
    .B(_054_),
    .C(_027_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _151_ (
    .A1(bit_cnt[0]),
    .A2(_079_),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _152_ (
    .A1(_027_),
    .A2(_055_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _153_ (
    .A1(_078_),
    .A2(_036_),
    .B(bit_cnt[2]),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _154_ (
    .A1(_027_),
    .A2(_037_),
    .A3(_056_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _155_ (
    .A1(uart_cstate[0]),
    .A2(uart_mode),
    .A3(_079_),
    .A4(_033_),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _156_ (
    .I0(rx_shift_reg[6]),
    .I1(rx_shift_reg[7]),
    .S(_057_),
    .Z(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _157_ (
    .I0(rx_shift_reg[5]),
    .I1(rx_shift_reg[6]),
    .S(_057_),
    .Z(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _158_ (
    .I0(rx_shift_reg[4]),
    .I1(rx_shift_reg[5]),
    .S(_057_),
    .Z(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _159_ (
    .I0(rx_shift_reg[3]),
    .I1(rx_shift_reg[4]),
    .S(_057_),
    .Z(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _160_ (
    .A1(tx_data_i[7]),
    .A2(_045_),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _161_ (
    .A1(_066_),
    .A2(_047_),
    .B(_058_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _162_ (
    .I0(rx_shift_reg[2]),
    .I1(rx_shift_reg[3]),
    .S(_057_),
    .Z(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _163_ (
    .I0(rx_shift_reg[1]),
    .I1(rx_shift_reg[2]),
    .S(_057_),
    .Z(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _164_ (
    .I0(rx_shift_reg[7]),
    .I1(uart_rx_sync[1]),
    .S(_057_),
    .Z(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _165_ (
    .I0(rx_shift_reg[0]),
    .I1(rx_shift_reg[1]),
    .S(_057_),
    .Z(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _166_ (
    .I0(tx_data_i[6]),
    .I1(tx_shift_reg[8]),
    .S(_045_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _167_ (
    .I0(tx_shift_reg[7]),
    .I1(_059_),
    .S(_048_),
    .Z(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _168_ (
    .A1(_062_),
    .A2(_034_),
    .B(_045_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _169_ (
    .I0(tx_data_i[5]),
    .I1(tx_shift_reg[7]),
    .S(_045_),
    .Z(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _170_ (
    .I0(tx_shift_reg[6]),
    .I1(_060_),
    .S(_048_),
    .Z(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _171_ (
    .I0(tx_data_i[4]),
    .I1(tx_shift_reg[6]),
    .S(_045_),
    .Z(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _172_ (
    .I0(tx_shift_reg[5]),
    .I1(_061_),
    .S(_048_),
    .Z(_025_)
  );
  (* src = "../../rtl/uart_simple.sv:63.3-71.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _173_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(bit_cnt[0]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:63.3-71.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _174_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(bit_cnt[1]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:63.3-71.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _175_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(bit_cnt[2]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _176_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(tx_shift_reg[0]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _177_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(tx_shift_reg[1]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _178_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(tx_shift_reg[2]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _179_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(tx_shift_reg[3]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _180_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(tx_shift_reg[4]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _181_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(tx_shift_reg[5]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _182_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(tx_shift_reg[6]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _183_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(tx_shift_reg[7]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:88.3-96.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _184_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(tx_shift_reg[8]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _185_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(rx_shift_reg[0]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _186_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(rx_shift_reg[1]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _187_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(rx_shift_reg[2]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _188_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(rx_shift_reg[3]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _189_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(rx_shift_reg[4]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _190_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(rx_shift_reg[5]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _191_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(rx_shift_reg[6]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:76.3-82.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _192_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(rx_shift_reg[7]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:101.3-109.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _193_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(uart_mode),
    .RN(rst_ni)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _194_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(uart_cstate[0]),
    .SETN(rst_ni)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _195_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(uart_cstate[1]),
    .RN(rst_ni)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _196_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(uart_cstate[2]),
    .RN(rst_ni)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _197_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(uart_cstate[3]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _198_ (
    .CLK(clk_i),
    .D(_000_[0]),
    .Q(clk_cnt[0]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _199_ (
    .CLK(clk_i),
    .D(_000_[1]),
    .Q(clk_cnt[1]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _200_ (
    .CLK(clk_i),
    .D(_000_[2]),
    .Q(clk_cnt[2]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _201_ (
    .CLK(clk_i),
    .D(_000_[3]),
    .Q(clk_cnt[3]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _202_ (
    .CLK(clk_i),
    .D(_000_[4]),
    .Q(clk_cnt[4]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:46.3-58.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _203_ (
    .CLK(clk_i),
    .D(_000_[5]),
    .Q(clk_cnt[5]),
    .RN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:33.3-39.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _204_ (
    .CLK(clk_i),
    .D(uart_rx_i),
    .Q(uart_rx_sync[0]),
    .SETN(rst_ni)
  );
  (* src = "../../rtl/uart_simple.sv:33.3-39.6" *)
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _205_ (
    .CLK(clk_i),
    .D(uart_rx_sync[0]),
    .Q(uart_rx_sync[1]),
    .SETN(rst_ni)
  );
  assign uart_rx_filtered = uart_rx_sync[1];
  assign uart_tx_o = tx_shift_reg[0];
  assign rx_data_o = rx_shift_reg;
endmodule
